theme: minima
# 网站的基本配置
title: Your Site Title
description: Your Site Description
baseurl: "" # 如果网站部署在子目录下，需要设置为子目录名称
url: "https://turadh.github.io/skills-github-pages" # 你的 GitHub Pages 网站地址

# Jekyll 配置
markdown: kramdown
permalink: /:year/:month/:day/:title/
paginate: 5 # 每页显示的文章数量
